/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_bigview_MainActivity */

#ifndef _Included_com_example_bigview_MainActivity
#define _Included_com_example_bigview_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_bigview_MainActivity
 * Method:    begin
 * Signature: (Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_com_example_bigview_MainActivity_begin
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     com_example_bigview_MainActivity
 * Method:    writeFrame
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_bigview_MainActivity_writeFrame
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_example_bigview_MainActivity
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_bigview_MainActivity_end
  (JNIEnv *, jclass);

/*
 * Class:     com_example_bigview_MainActivity
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_bigview_MainActivity_release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
